server:
  port: 8092

thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

spring:
  config:
    import:
      - classpath:agent/test-agent.yml
      - classpath:agent/mcp-test-agent.yml
      - classpath:agent/contact-web-agent.yml
      - classpath:agent/contact-app-agent.yml
  datasource:
    username: root
    password: ${MYSQL_ROOT_PASSWORD:wangjin@test}
    url: jdbc:mysql://mysql:3306/agent_scaffold?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    pool-name: Retail_HikariCP
    minimum-idle: 5
    idle-timeout: 180000
    maximum-pool-size: 15
    auto-commit: true
    max-lifetime: 1800000
    connection-timeout: 30000
    connection-test-query: SELECT 1
  type: com.zaxxer.hikari.HikariDataSource

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  metrics:
    tags:
      application: agent-scaffold

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
